import MainContainer from "../components/MainContainer";
import Head from "next/head"

export default function Home() {

    return (
        <div>
            <Head>
                <meta keywords="next.js"/>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <MainContainer/>
        </div>
    )
}